spring.application.name=MarketHub

spring.datasource.url=jdbc:postgresql://localhost:5432/MarketHub
spring.datasource.username=postgres
spring.datasource.password=ihsanmee

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update